In [1]:
import autosklearn.classification
import sklearn.model_selection
import sklearn.datasets
import sklearn.metrics

if __name__ == "__main__":
    X, y = sklearn.datasets.load_digits(return_X_y=True)
    X_train, X_test, y_train, y_test = \
        sklearn.model_selection.train_test_split(X, y, random_state=1)
    automl = autosklearn.classification.AutoSklearnClassifier()
    automl.fit(X_train, y_train)
    y_hat = automl.predict(X_test)
    print("Accuracy score", sklearn.metrics.accuracy_score(y_test, y_hat))

ModuleNotFoundError: No module named 'autosklearn'

In [3]:
#import sys
#sys.version

'3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)]'

In [12]:
pip install auto-sklearn

  Using cached auto-sklearn-0.15.0.tar.gz (6.5 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
Note: you may need to restart the kernel to use updated packages.


  error: subprocess-exited-with-error
  
  Getting requirements to build wheel did not run successfully.
  exit code: 1
  
  [20 lines of output]
  Traceback (most recent call last):
    File "C:\Users\User\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\Users\User\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\User\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\User\AppData\Local\Temp\pip-build-env-h8t86_0q\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
      return self._get_build_requires(config

In [6]:
pip install auto-ml

     ---------------------------------------- 0.0/71.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/71.6 kB ? eta -:--:--
     ----- ---------------------------------- 10.2/71.6 kB ? eta -:--:--
     ---------------- --------------------- 30.7/71.6 kB 325.1 kB/s eta 0:00:01
     -------------------------------------- 71.6/71.6 kB 490.9 kB/s eta 0:00:00
     ---------------------------------------- 0.0/150.7 kB ? eta -:--:--
     ------------------------------ ------- 122.9/150.7 kB 3.6 MB/s eta 0:00:01
     -------------------------------------- 150.7/150.7 kB 3.0 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
     ---------------------------------------- 0.0/301.1 kB ? eta -:--:--
     -------------------------------------  297.0/301.1 kB 9.2 MB/s eta 0:00:01
     -------------------------------------- 301.1/301.1 kB 9.4 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing me

  error: subprocess-exited-with-error
  
  Preparing metadata (pyproject.toml) did not run successfully.
  exit code: 1
  
  [62 lines of output]
  <string>:17: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  Partial import of sklearn during the build process.
  <string>:116: DeprecationWarning:
  
    `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
    of the deprecation of `distutils` itself. It will be removed for
    Python >= 3.12. For older Python versions it will remain present.
    It is recommended to use `setuptools < 60.0` for those Python versions.
    For more details, see:
      https://numpy.org/devdocs/reference/distutils_status_migration.html
  
  
  INFO: No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  Traceback (most recent call last):
    File "C:\Users\User\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_proces

In [56]:
#install required libraries
from sklearn.preprocessing import OneHotEncoder, RobustScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.dummy import DummyClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier, ExtraTreesClassifier
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier
from sklearn.svm import SVC

from sklearn.metrics import accuracy_score, ConfusionMatrixDisplay, confusion_matrix, fbeta_score, precision_score, \
                            recall_score, roc_auc_score, classification_report, f1_score, roc_curve
                            
from sklearn.base import TransformerMixin
from sklearn.decomposition import PCA
from sklearn.model_selection import StratifiedShuffleSplit, StratifiedKFold, GridSearchCV

import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import warnings


warnings.filterwarnings("ignore")
%matplotlib inline

In [8]:
#Read Data
#load downloaded file
INPUT_PATH = r"C:\Users\User\Desktop\portfolio\cc_defaulter_prediction\artifacts\data_ingestion\CreditCardClients.xls"
df = pd.read_excel(INPUT_PATH, header=1)
#drop id colum
df.drop(columns='ID', inplace=True)
#rename columns for convenience
df.rename(columns = {'PAY_0': 'PAY_1', 'default payment next month': 'Default'}, inplace=True)

#lowering column names 
df.columns = [col.lower() for col in df.columns]
#split the data based on class label
split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=33)
# Use the split method to get the indices for training and testing
strat_train_set = None
strat_test_set = None
for train_idx, test_idx in split.split(df, df.iloc[:,-1]):
    df_train = df.loc[train_idx]
    df_test = df.loc[test_idx]
            

In [9]:
df.columns

Index(['limit_bal', 'sex', 'education', 'marriage', 'age', 'pay_1', 'pay_2',
       'pay_3', 'pay_4', 'pay_5', 'pay_6', 'bill_amt1', 'bill_amt2',
       'bill_amt3', 'bill_amt4', 'bill_amt5', 'bill_amt6', 'pay_amt1',
       'pay_amt2', 'pay_amt3', 'pay_amt4', 'pay_amt5', 'pay_amt6', 'default'],
      dtype='object')

In [10]:
class FeatureGenerator(TransformerMixin):
    
    '''
    Upon calling fit_transform or transform method this column generates new dataframe columns
    '''
    def __init__(self):
      
        try:
            self.bill_amt1_ix = "bill_amt1"
            self.bill_amt2_ix = "bill_amt2"
            self.bill_amt3_ix = "bill_amt3"
            self.bill_amt4_ix = "bill_amt4"
            self.bill_amt5_ix = "bill_amt5"
            self.bill_amt6_ix = "bill_amt6"
            self.limit_bal_ix = "limit_bal"
            self.pay_amt1_ix = "pay_amt1"
            self.pay_amt2_ix = "pay_amt2"
            self.pay_amt3_ix = "pay_amt3"
            self.pay_amt4_ix = "pay_amt4"
            self.pay_amt5_ix = "pay_amt5"
            self.pay_amt6_ix = "pay_amt6"
            

        except Exception as e:
            print(e)


    def fit(self, X):
        return self

    def transform(self, X):
        '''
            X['leverage_1'] = X[self.bill_amt1_ix]/X[self.limit_bal_ix]   
            X['leverage_2'] = X[self.bill_amt2_ix]/X[self.limit_bal_ix]
            X['leverage_3'] = X[self.bill_amt3_ix]/X[self.limit_bal_ix]
            X['leverage_4'] = X[self.bill_amt4_ix]/X[self.limit_bal_ix]
            X['leverage_5'] = X[self.bill_amt5_ix]/X[self.limit_bal_ix]
            X['leverage_6'] = X[self.bill_amt6_ix]/X[self.limit_bal_ix]

            X['bill_to_pay1'] = X[self.bill_amt1_ix]/(X[self.pay_amt1_ix]+1)   
            X['bill_to_pay2'] = X[self.bill_amt2_ix]/(X[self.pay_amt2_ix]+1)
            X['bill_to_pay3'] = X[self.bill_amt3_ix]/(X[self.pay_amt3_ix]+1)
            X['bill_to_pay4'] = X[self.bill_amt4_ix]/(X[self.pay_amt4_ix]+1)
            X['bill_to_pay5'] = X[self.bill_amt5_ix]/(X[self.pay_amt5_ix]+1)
            X['bill_to_pay6'] = X[self.bill_amt6_ix]/(X[self.pay_amt6_ix]+1)
            
            X['overdraft'] = np.where(   (X[self.bill_amt1_ix]>X[self.limit_bal_ix]) |
                                        (X[self.bill_amt2_ix]>X[self.limit_bal_ix]) |
                                        (X[self.bill_amt3_ix]>X[self.limit_bal_ix]) |
                                        (X[self.bill_amt4_ix]>X[self.limit_bal_ix]) |
                                        (X[self.bill_amt5_ix]>X[self.limit_bal_ix]) |
                                        (X[self.bill_amt6_ix]>X[self.limit_bal_ix]),
                                        1, 0                                 
                                    )
        '''
        X['avg_bill_amt'] = (X[self.bill_amt1_ix]+X[self.bill_amt2_ix]+X[self.bill_amt3_ix] \
                                     +X[self.bill_amt4_ix]+X[self.bill_amt5_ix]+X[self.bill_amt6_ix])/6
        X['avg_leverage_ratio'] = (X[self.bill_amt1_ix]+X[self.bill_amt2_ix]+X[self.bill_amt3_ix] \
                                       +X[self.bill_amt4_ix]+X[self.bill_amt5_ix]+X[self.bill_amt6_ix])/(6*X[self.limit_bal_ix])
        X['avg_pay_amt'] = (X[self.pay_amt1_ix]+X[self.pay_amt2_ix]+X[self.pay_amt3_ix] \
                                      +X[self.pay_amt4_ix]+X[self.pay_amt5_ix]+X[self.pay_amt6_ix])/6
        X['avg_bill_to_pay'] = (X[self.bill_amt1_ix]+X[self.bill_amt2_ix]+X[self.bill_amt3_ix] \
                                       +X[self.bill_amt4_ix]+X[self.bill_amt5_ix]+X[self.bill_amt6_ix])/ \
                                        ((X[self.pay_amt1_ix]+X[self.pay_amt2_ix]+X[self.pay_amt3_ix] \
                                       +X[self.pay_amt4_ix]+X[self.pay_amt5_ix]+X[self.pay_amt6_ix])+1)

        return X


In [11]:

def preprocess1(numeric_features, categorical_features):#, model_name, model):
    '''
    input: list of numerical features and categorical features
    applies transformers on given data
    returns: preprocessed object
    '''
    
    # Create transformers
    categorical_transformer = OneHotEncoder()
    feature_generator = FeatureGenerator()
    
    # Create transformers
    numeric_transformer = Pipeline(steps=[('scaler', RobustScaler())])

    categorical_transformer = Pipeline(steps=[('onehot', OneHotEncoder(handle_unknown='ignore'))])

        # Create a column transformer
    preprocessor = ColumnTransformer(
        transformers=[
            ('num', numeric_transformer, numeric_features),
            ('cat', categorical_transformer, categorical_features)
        ])

    # Create the pipeline
    pipeline = Pipeline(steps=[('feature generator', feature_generator),('preprocessor', preprocessor)])
    
    return pipeline

In [48]:
sum(pca.explained_variance_ratio_)

0.9998129917690063

In [49]:
pca.explained_variance_ratio_

array([0.99981299])

In [50]:
#helper functions
def evaluate_clf(true, predicted):
    '''
    Input: True values and Predicted values
    Returns: Accuracy, F1-Score, Precision, Recall, Roc-auc Score
    '''
    acc = accuracy_score(true, predicted) # Calculate Accuracy
    f1 = f1_score(true, predicted) # Calculate F1-score
    precision = precision_score(true, predicted) # Calculate Precision
    recall = recall_score(true, predicted)  # Calculate Recall
    roc_auc = roc_auc_score(true, predicted) #Calculate Roc
    return acc, f1 , precision, recall, roc_auc

In [51]:
#print confusion matrix and classification report
def display_confusion_matrix(y_true, y_pred, labels):
    '''
    This function takes y_ture, y_predicted, class labels and returns false positives and false negatives
   
    '''
    # Create confusion matrix
    cm = confusion_matrix(y_true, y_pred, labels=labels)#, normalize='all')
    print("Confusion Matrix: \n", cm)
    print("Classification Report: \n", classification_report(y_true, y_pred, labels=labels))

In [52]:
# Create a function which can evaluate models and return a report 

def evaluate_models(X_train, y_train, x_test, y_test, models):
    '''
    This function takes in X and y and models dictionary as input
   
    Iterates through the given model dictionary and evaluates the metrics
    Returns: Dataframe which contains report of all models metrics with cost
    '''
   
    
    models_list = []
    model_train_accuracy_list = []
    train_f1 = []
    test_f1 = []
    model_test_accuracy_list = []
    #train_roc = []
    #test_roc =[]
    f2_score = []
    

    for i in range(len(list(models))):
        model = list(models.values())[i]
        model.fit(X_train, y_train) # Train model

        # Make predictions
        y_train_pred = model.predict(X_train)
        y_test_pred = model.predict(x_test)

        # Training set performance
        model_train_accuracy, model_train_f1,model_train_precision,\
        model_train_recall,model_train_rocauc_score=evaluate_clf(y_train ,y_train_pred)


        # Test set performance
        model_test_accuracy,model_test_f1,model_test_precision,\
        model_test_recall,model_test_rocauc_score=evaluate_clf(y_test, y_test_pred)
        
        print(list(models.keys())[i])
        models_list.append(list(models.keys())[i])
        model_train_accuracy_list.append(model_train_accuracy)
        model_test_accuracy_list.append(model_test_accuracy)
        train_f1.append(model_train_f1)
        test_f1.append(model_test_f1)
        #train_roc.append(model_train_rocauc_score)
        #test_roc.append(model_test_rocauc_score)
        f2_score.append(fbeta_score(y_test, y_test_pred, beta=2))

        print('Model performance for Training set')
        print("- Accuracy: {:.4f}".format(model_train_accuracy))
        print('- F1 score: {:.4f}'.format(model_train_f1)) 
        #print('- Precision: {:.4f}'.format(model_train_precision))
        #print('- Recall: {:.4f}'.format(model_train_recall))
        print('- Roc Auc Score: {:.4f}'.format(model_train_rocauc_score))
        display_confusion_matrix(y_train, y_train_pred, model.classes_)


        print('----------------------------------')

        print('Model performance for Test set')
        print('- Accuracy: {:.4f}'.format(model_test_accuracy))
        print('- F1 score: {:.4f}'.format(model_test_f1))
        #print('- Precision: {:.4f}'.format(model_test_precision))
        #print('- Recall: {:.4f}'.format(model_test_recall))
        print('- Roc Auc Score: {:.4f}'.format(model_test_rocauc_score))
        display_confusion_matrix(y_test, y_test_pred, model.classes_)

        
        print('='*35)
        print('\n')
        
    report_data = {
        'Model Name': models_list,
        'Train Accuracy': model_train_accuracy_list,
      #  'Train_ROC_AUC_score': train_roc,
        'Test Accuracy': model_test_accuracy_list,
        'Train_F1': train_f1,

        'Test_F1': test_f1,
      #  'Test_ROC_AUC_score': test_roc
        'F2-Score':f2_score
    }
    
    report = pd.DataFrame(report_data).sort_values(by=['F2-Score', 'Test_F1'], ascending=False)        
    return report

In [57]:
#list of classification models
models = {
    "Baseline Classifier": DummyClassifier(strategy='most_frequent'),
    "Logistic Regression": LogisticRegression(class_weight='balanced'),
    "SVM": SVC(class_weight='balanced'),
    "Decision Tree": DecisionTreeClassifier(class_weight='balanced'),
    "Random Forest": RandomForestClassifier(class_weight='balanced'),
    "Gradient Boost": GradientBoostingClassifier(),
    "Adaboost": AdaBoostClassifier(),
    "Extra tree": ExtraTreesClassifier(class_weight='balanced'),
    "XGBoost": XGBClassifier()
}

In [58]:
categorical_features = ['sex', 'education', 'marriage','pay_1', 'pay_2', 'pay_3', 'pay_4', 'pay_5', 'pay_6']
numeric_cols = ['age','limit_bal', 'bill_amt1', 'bill_amt2', 'bill_amt3', 'bill_amt4', 'bill_amt5', 'bill_amt6', \
                 'pay_amt1', 'pay_amt2', 'pay_amt3', 'pay_amt4', 'pay_amt5', 'pay_amt6']
engineered_cols = ['avg_bill_amt', 'avg_leverage_ratio', 'avg_pay_amt', 'avg_bill_to_pay']
X_train = df_train.drop('default', axis=1)
y_train = df_train['default']

x_test=df_test.drop('default', axis=1)
y_test=df_test['default']
num_cols = numeric_cols+engineered_cols
pipeline = preprocess1(num_cols, categorical_features)
X_train_transformed = pipeline.fit_transform(X_train)
x_test_transformed = pipeline.transform(x_test)
column_names = pipeline[1:].named_steps['preprocessor'].get_feature_names_out()
X_train_transformed_df = pd.DataFrame(X_train_transformed.toarray(), columns = column_names)
x_test_transformed_df = pd.DataFrame(x_test_transformed.toarray(), columns = column_names)

In [63]:
pca = PCA(n_components = 10)
X_train_pca = pca.fit_transform(X_train_transformed_df)
x_test_pca = pca.transform(x_test_transformed_df)

In [64]:
pca.explained_variance_ratio_

array([9.99812992e-01, 6.36458111e-05, 2.77449392e-05, 2.21015713e-05,
       1.95314043e-05, 1.82838242e-05, 1.58649723e-05, 1.09976646e-05,
       1.59953663e-06, 9.51366271e-07])

In [65]:
report1 = evaluate_models(X_train=X_train_pca, y_train=y_train, x_test=x_test_pca, y_test=y_test, models=models)
report1  

Baseline Classifier
Model performance for Training set
- Accuracy: 0.7788
- F1 score: 0.0000
- Roc Auc Score: 0.5000
Confusion Matrix: 
 [[18691     0]
 [ 5309     0]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.78      1.00      0.88     18691
           1       0.00      0.00      0.00      5309

    accuracy                           0.78     24000
   macro avg       0.39      0.50      0.44     24000
weighted avg       0.61      0.78      0.68     24000

----------------------------------
Model performance for Test set
- Accuracy: 0.7788
- F1 score: 0.0000
- Roc Auc Score: 0.5000
Confusion Matrix: 
 [[4673    0]
 [1327    0]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.78      1.00      0.88      4673
           1       0.00      0.00      0.00      1327

    accuracy                           0.78      6000
   macro avg       0.39      0.50      0.44      6000
weighted

XGBoost
Model performance for Training set
- Accuracy: 0.8759
- F1 score: 0.6354
- Roc Auc Score: 0.7373
Confusion Matrix: 
 [[18427   264]
 [ 2714  2595]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.87      0.99      0.93     18691
           1       0.91      0.49      0.64      5309

    accuracy                           0.88     24000
   macro avg       0.89      0.74      0.78     24000
weighted avg       0.88      0.88      0.86     24000

----------------------------------
Model performance for Test set
- Accuracy: 0.7887
- F1 score: 0.3361
- Roc Auc Score: 0.5929
Confusion Matrix: 
 [[4411  262]
 [1006  321]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.81      0.94      0.87      4673
           1       0.55      0.24      0.34      1327

    accuracy                           0.79      6000
   macro avg       0.68      0.59      0.61      6000
weighted avg       0

Model Name  Train Accuracy  Test Accuracy  Train_F1   Test_F1  \
1  Logistic Regression        0.556667       0.555333  0.412220  0.407638   
3        Decision Tree        0.999417       0.703667  0.998683  0.334082   
8              XGBoost        0.875917       0.788667  0.635406  0.336126   
7           Extra tree        0.999417       0.793333  0.998683  0.298643   
4        Random Forest        0.999500       0.788500  0.998871  0.288278   
5       Gradient Boost        0.800500       0.794667  0.296089  0.276146   
6             Adaboost        0.788583       0.785000  0.202703  0.189698   
2                  SVM        0.776875       0.777333  0.062992  0.052482   
0  Baseline Classifier        0.778792       0.778833  0.000000  0.000000   

   F2-Score  
1  0.540955  
3  0.335288  
8  0.272449  
7  0.229605  
4  0.222935  
5  0.206757  
6  0.135475  
2  0.034316  
0  0.000000